### ISSUE TITLE
2.5.7 Not working on OSX Catalina

### ISSUE THREAD

**Issue by gustavolanzas** [moshfeu/y2mp3#124]
**Describe the bug**
No search when a URL is entered into the search field. Opening the dev console shows a warning about the Node.js vm module being deprecated, and a couple of TypeErrors.

**To Reproduce**
1. Install 2.5.7 build on OSX 
2. Paste in YT url
3. Click magnifying glass

**Add logs from DevTools**

```
node:electron/js2c/renderer_init:33 The vm module of Node.js is deprecated in the renderer process and will be removed.
o._load @ node:electron/js2c/renderer_init:33

path.ts:29 ffmpegPath /Users/audioel/Library/Application Support/y2mp3/ffmpeg

index.es.js:1275 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'request')
    at app.bundle.js:2:2087200
    at new Promise (<anonymous>)
    at app.bundle.js:2:2086082
    at async app.bundle.js:2:2092437
    
api.ts:97 TypeError: Cannot read properties of undefined (reading 'twoColumnBrowseResultsRenderer')
    at playlist-scraper.ts:19:21
    at async api.ts:85:11
    at async Vr.search (store.ts:35:13)
    at async api.ts:128:30

```
**Expected behavior**
App would open playlist.

**Screenshots**
![Screen Shot 2023-04-02 at 12 05 32 PM](https://user-images.githubusercontent.com/1471172/229373602-f3917034-6f55-4f78-acb5-c336940df092.png)

 - OS: OSX Catalina
 - Version:  10.15.7
 - App Version: 2.5.7

**Additional context**
Same issue seems to happen with 2.5.5

**Comment by gustavolanzas** [comment]
My apologies - this was due to having the playlist set to private. Changing the status to "unlisted" or "public" fixes the issue.

**Comment by moshfeu** [comment]
Thank you for both reporting and following up :)
I'll keep this issue open for adding a user friendly error message but the severity is lower.
