### ISSUE TITLE
Blank app when no "downloads" folder in home

### ISSUE THREAD

**Issue by mjeammet** [moshfeu/y2mp3#136]
Hi 👋🏽 ,

**Describe the bug**
Blank app upon launching. Everything under "Application" menu is non-responsive.

**To Reproduce**
1. Install Ubuntu with non-English language, I guess
2. Download AppImage, make it executable
3. Launch the app

**Screenshots**
![image](https://github.com/moshfeu/y2mp3/assets/30848497/ad6210a1-0196-4882-b4f8-df344ba843d5)

**Add logs from DevTools**

```
Uncaught Error: ENOENT: no such file or directory, mkdir '/home/marie/downloads/y2mp3'
    at mkdirSync (node:fs:1334:3)
    at file:///tmp/.mount_y2mp3-IMxfqy/resources/app.asar/resources/app.bundle.js:2:1800618
    at file:///tmp/.mount_y2mp3-IMxfqy/resources/app.asar/resources/app.bundle.js:2:1983090
    at file:///tmp/.mount_y2mp3-IMxfqy/resources/app.asar/resources/app.bundle.js:2:1983094
```

 - OS: Ubuntu
 - App Version [e.g. 1.0.1]

**🔨  Fix**
My system is in french so my "downloads" folder is actually called "Téléchargements". I just added a "downloads" directory, relaunched the app and 🎉 .

**Comment by moshfeu** [comment]
Thanks for reporting @mjeammet!
I didn't think about other languages 😅
Maybe I'll try to find the download folder but if I can't find, I'll ask the user to selectnthe folder
