### ISSUE TITLE
Language change

### ISSUE THREAD

**Issue by oguzsaka** [moshfeu/y2mp3#52]
selectable language function can be added.
If you send me the language file I can help with the translation

**Comment by oguzsaka** [comment]
https://www.christianengvall.se/electron-localization/

**Comment by moshfeu** [comment]
Thank you, Good idea!
Want to help and implement it?

**Comment by oguzsaka** [comment]
I've just started learning Electron JS. When I saw your project, I gave up. I am a software developer and I have skills in html js php .net. I would like to help you learn Electron

**Comment by moshfeu** [comment]
Why you gave up? Also, I'm curious, how did you find this project?

**Comment by oguzsaka** [comment]
You really designed it. it only gives a security warning when installing the software (Win10).
Design changes can help

**Comment by oguzsaka** [comment]
it makes more sense to help and develop the car's engine rather than re-design it when someone has designed it

**Comment by moshfeu** [comment]
Yah, I'm not a designer :)
I'm appreciating any feedback you have and if you want to contribute to this project, I'll glad to help you with that.

**Comment by oguzsaka** [comment]
Of course I would like to contribute. I want to learn both electron :)

**Comment by moshfeu** [comment]
Great! So you want to try to take and work on this issue?

**Comment by oguzsaka** [comment]
yes but I have basic knowledge of electron js

**Comment by moshfeu** [comment]
No rush. You can give a shot. Review the code, if you have questions, let me know.

**Comment by oguzsaka** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/7862838/70852112-b4855080-1eae-11ea-9345-71f6dbc0bc8c.PNG)

?

**Comment by moshfeu** [comment]
What are you trying to do?
To run it locally: `npm start` (or `yarn start`)
To build the app locally: `npm run build` (or `yarn build`)

**Comment by oguzsaka** [comment]
thanks :) I am also experimenting with language file

**Comment by moshfeu** [comment]
Great! Let me know how it goes.

**Comment by oguzsaka** [comment]
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v12.13.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle y2mp3@2.4.0~prebuild: y2mp3@2.4.0
6 info lifecycle y2mp3@2.4.0~build: y2mp3@2.4.0
7 verbose lifecycle y2mp3@2.4.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle y2mp3@2.4.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\electron\y2mp3\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Git\cmd;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files\nodejs\;C:\Users\oguzs\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\JetBrains\PhpStorm 2019.1.1\bin;;C:\Users\oguzs\AppData\Roaming\Composer\vendor\bin;C:\Users\oguzs\AppData\Roaming\npm
9 verbose lifecycle y2mp3@2.4.0~build: CWD: C:\electron\y2mp3
10 silly lifecycle y2mp3@2.4.0~build: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'npm run generate-icons && tsc && webpack --config webpack.prod.js'
10 silly lifecycle ]
11 silly lifecycle y2mp3@2.4.0~build: Returned: code: 2  signal: null
12 info lifecycle y2mp3@2.4.0~build: Failed to exec build script
13 verbose stack Error: y2mp3@2.4.0 build: `npm run generate-icons && tsc && webpack --config webpack.prod.js`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid y2mp3@2.4.0
15 verbose cwd C:\electron\y2mp3
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.13.1
19 verbose npm  v6.12.1
20 error code ELIFECYCLE
21 error errno 2
22 error y2mp3@2.4.0 build: `npm run generate-icons && tsc && webpack --config webpack.prod.js`
22 error Exit status 2
23 error Failed at the y2mp3@2.4.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
`

**Comment by oguzsaka** [comment]
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v12.13.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle y2mp3@2.4.0~prebuild: y2mp3@2.4.0
6 info lifecycle y2mp3@2.4.0~build: y2mp3@2.4.0
7 verbose lifecycle y2mp3@2.4.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle y2mp3@2.4.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\electron\y2mp3\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Git\cmd;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files\nodejs\;C:\Users\oguzs\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\JetBrains\PhpStorm 2019.1.1\bin;;C:\Users\oguzs\AppData\Roaming\Composer\vendor\bin;C:\Users\oguzs\AppData\Roaming\npm
9 verbose lifecycle y2mp3@2.4.0~build: CWD: C:\electron\y2mp3
10 silly lifecycle y2mp3@2.4.0~build: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'npm run generate-icons && tsc && webpack --config webpack.prod.js'
10 silly lifecycle ]
11 silly lifecycle y2mp3@2.4.0~build: Returned: code: 2  signal: null
12 info lifecycle y2mp3@2.4.0~build: Failed to exec build script
13 verbose stack Error: y2mp3@2.4.0 build: `npm run generate-icons && tsc && webpack --config webpack.prod.js`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid y2mp3@2.4.0
15 verbose cwd C:\electron\y2mp3
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.13.1
19 verbose npm  v6.12.1
20 error code ELIFECYCLE
21 error errno 2
22 error y2mp3@2.4.0 build: `npm run generate-icons && tsc && webpack --config webpack.prod.js`
22 error Exit status 2
23 error Failed at the y2mp3@2.4.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by moshfeu** [comment]
What is that?

**Comment by oguzsaka** [comment]
npm run build
