### ISSUE TITLE
When trying to run appimage on Ubuntu 20.04

### ISSUE THREAD

**Issue by zerofill** [moshfeu/y2mp3#72]
Following is output if attempting to run it via command line, since it wouldn't start normally.

A JavaScript error occurred in the main process
Uncaught Exception:
/tmp/.mount_y2mp3-GmWcak/resources/app.asar/main.js:1
import { app, Menu, shell, BrowserWindow, Tray, ipcMain, } from 'electron';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1051:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Object.<anonymous> (electron/js2c/browser_init.js:185:3494)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:185:3698)
    at __webpack_require__ (electron/js2c/browser_init.js:1:128)
    at electron/js2c/browser_init.js:1:1200

**Comment by moshfeu** [comment]
Thanks for the issue.
I'll try to look at it as soon as I can

**Comment by moshfeu** [comment]
Can you download and try 2.5.4 please?
Thanks!

https://github.com/moshfeu/y2mp3/releases/tag/v2.5.4

**Comment by moshfeu** [comment]
Seems like the same issue as #73 which solved.
If it still exists, please open a new issue.

Thanks!
